### ISSUE TITLE
TypeError: Cannot assign to read only property 'string' of (begin)

### ISSUE THREAD

**Issue by kristianmandrup** [tav/nodelint#40]
``` sh
19:09 $ nodelint apps/_global/data
undefined:2557
        s.string = s;
                 ^

TypeError: Cannot assign to read only property 'string' of (begin)
    at ultimate (eval at <anonymous> (/Users/kristianmandrup/npm/lib/node_modules/nodelint/nodelint:46:11), <anonymous>:2557:18)
    at eval (eval at <anonymous> (/Users/kristianmandrup/npm/lib/node_modules/nodelint/nodelint:46:11), <anonymous>:3167:5)
    at eval (eval at <anonymous> (/Users/kristianmandrup/npm/lib/node_modules/nodelint/nodelint:46:11), <anonymous>:6399:2)
    at /Users/kristianmandrup/npm/lib/node_modules/nodelint/nodelint:46:3
    at Object.<anonymous> (/Users/kristianmandrup/npm/lib/node_modules/nodelint/nodelint:194:2)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
✘-1 ~/repos/test123/repo-manager-v3 [master|✚ 3…14] 
19:09 $ ls apps/_global/data
available feeds     forms     index.js  lists     menus
```

**Comment by fauria** [comment]
Same issue here (OSX).

```
$ npm -v
2.14.2
$ node -v
v0.12.7
```

**Comment by gregory-nisbet** [comment]
Same here on ubuntu 15.04 vm

```
$ node --version; npm --version; uname -a; nodelint
v0.12.6
2.11.2
Linux g-virtual-machine-vivid 3.19.0-30-generic #34-Ubuntu SMP Fri Oct 2 22:08:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
undefined:2557
        s.string = s;
                 ^
TypeError: Cannot assign to read only property 'string' of (begin)
    at ultimate (eval at <anonymous> (/usr/local/lib/node_modules/nodelint/nodelint:46:11), <anonymous>:2557:18)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/nodelint/nodelint:46:11), <anonymous>:3167:5)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/nodelint/nodelint:46:11), <anonymous>:6399:2)
    at /usr/local/lib/node_modules/nodelint/nodelint:46:3
    at Object.<anonymous> (/usr/local/lib/node_modules/nodelint/nodelint:194:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

This error seems to be happening because we are `eval`ing `/usr/local/lib/nodelint/jslint/jslint.js`... 
`s.string = s` is on line 2557. ... Why are not requiring jslint as a normal dependency instead of evaling it?

**Comment by tsoernes** [comment]
+1

**Comment by m-vdb** [comment]
+1

**Comment by felipap** [comment]
+1

**Comment by monsur** [comment]
+1 

> node -v
> v4.0.0
> 
> npm -v
> 2.14.2

**Comment by monsur** [comment]
FWIW I think the root issue is somewhere in JSLint (or some interplay with JSLint and Node). The line number 46 in the error is a red herring, since that line just evals JSLint.

**Comment by brandonros** [comment]
Vaporware at the moment.

**Comment by PeterMK85** [comment]
+1

**Comment by jvopalensky** [comment]
+1

> C:\Projects\pusher>jake build
> (node) child_process: options.customFds option is deprecated. Use options.stdio instead.
> evalmachine.<anonymous>:2557
>         s.string = s;
>                  ^
> TypeError: Cannot assign to read only property 'string' of (begin)
>     at ultimate (evalmachine.<anonymous>:2557:18)
>     at evalmachine.<anonymous>:3167:5
>     at evalmachine.<anonymous>:6399:2
>     at Object.exports.runInContext (vm.js:44:17)
>     at Object.<anonymous> (C:\Projects\pusher\node_modules\jslint\lib\nodelint.js:9:4)
>     at Module._compile (module.js:397:26)
>     at Object.Module._extensions..js (module.js:404:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>  jake aborted.
> Error: !!! JSLint FAILED. !!!
>     at api.fail (D:\Program Files\nodejs\node_modules\jake\lib\api.js:336:18)
>     at ChildProcess.<anonymous> (C:\Projects\pusher\Jakefile.js:52:7)
> (See full trace by running task with --trace)
> 
> node -v 
> 5.4.1
> 
> npm -v 
> 3.5.3

**Comment by wickedest** [comment]
+1
node -v
v4.2.6

npm -v
2.14.12

**Comment by wickedest** [comment]
I think this should be {{x.string = s;}} [jslint.js:2557](https://github.com/douglascrockford/JSLint/blob/4f2bf65ed59a0ba16fb22a6a90f76fc0060a2c22/jslint.js#L2557)

**Comment by neka-io** [comment]
I'm having the same problem and have tested with both node v4 & npm v2 and node v5 & npm v3 combinations.

**Comment by CutOffFrequency** [comment]
+1

**Comment by wickedest** [comment]
Can you cut a new version of this npm module with this fix?

**Comment by MaffooBristol** [comment]
Same here, OSX with Node 5.1.1

**Comment by markjohndoyle** [comment]
Same here:
Node: v4.4.5
nodelint: ^0.6.2

Windows 10 x64

**Comment by en0** [comment]
Pull Request https://github.com/tav/nodelint/pull/41 fixes ^

**Comment by rantrix** [comment]
Same here...

npm v3.9.5
node v6.2.1

**Comment by VOID404** [comment]
same here
npm v3.10.5
node v4.4.7

**Comment by tofupup** [comment]
+1

npm 3.10.8
node v6.8.1

**Comment by starkovv** [comment]
+1
npm 4.1.2
node 7.5.0
macOS 10.12.3

**Comment by randomstring** [comment]
After about 5 minutes of poking around I just commented out the line producing the error, and everything seems to work just fine now. *shrug*

```javascript
    function ultimate(s) {
        var x = symbol(s, 0);
        x.from = 1;
        x.thru = 1;
        x.line = 0;
        x.edge = 'edge';
        // s.string = s;
        return postscript(x);
    }
```

**Comment by tav** [comment]
Hey guys,

Sorry, this project hasn't been maintained in a long time 😞  While `nodelint` was great in the early days of Node.js, the world has moved on in terms of needing support for ES6+ syntax and we've not kept up.

Personally, I've been using [ESLint](https://github.com/eslint/eslint) for the last few years and it does a pretty decent job. There are also alternatives like [JSHint](https://github.com/jshint/jshint) if ESLint isn't to your liking for some reason.

Apologies for not making it clear that the project wasn't being maintained. I've now updated the repo info to mark that it's DEPRECATED.

A big thanks to those of you who did use it over the years though. Much appreciated!

— 
Cheers, tav

**Comment by suculent** [comment]
Wesome, thanks for fair suggestions.
