### ISSUE TITLE
crash when trying to run - Cannot create property 'string' on string '(begin)'

### ISSUE THREAD

**Issue by increpare** [tav/nodelint#44]
package version 0.6.2
node version 6.9.1
macOS 10.12

i installed from npm -

npm install -g nodelint

then when i try to run it

increpare:tools stephenlavelle$ nodelint
undefined:2557
        s.string = s;
                 ^

TypeError: Cannot create property 'string' on string '(begin)'
    at ultimate (eval at <anonymous> (/usr/local/Cellar/node/6.9.1/lib/node_modules/nodelint/nodelint:46:11), <anonymous>:2557:18)
    at eval (eval at <anonymous> (/usr/local/Cellar/node/6.9.1/lib/node_modules/nodelint/nodelint:46:11), <anonymous>:3167:5)
    at eval (eval at <anonymous> (/usr/local/Cellar/node/6.9.1/lib/node_modules/nodelint/nodelint:46:11), <anonymous>:6399:2)
    at /usr/local/Cellar/node/6.9.1/lib/node_modules/nodelint/nodelint:46:3
    at Object.<anonymous> (/usr/local/Cellar/node/6.9.1/lib/node_modules/nodelint/nodelint:194:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by masterprompt** [comment]
same

**Comment by mjainta** [comment]
same problem here

**Comment by suculent** [comment]
Seems like duplicate of https://github.com/tav/nodelint/issues/40

same here, node 5.9.0, macOS, nodelint both 0.6.2 && 0.5.2 tested.

`undefined:2776
        s.string = s;
                 ^

TypeError: Cannot assign to read only property 'string' of (begin)
    at ultimate (eval at <anonymous> (/usr/local/lib/node_modules/nodelint/nodelint:64:11), <anonymous>:2776:18)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/nodelint/nodelint:64:11), <anonymous>:3388:5)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/nodelint/nodelint:64:11), <anonymous>:6922:2)
    at /usr/local/lib/node_modules/nodelint/nodelint:64:3
    at Object.<anonymous> (/usr/local/lib/node_modules/nodelint/nodelint:200:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)`
